[package]
name = "msdf"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
png = "0.17"
ttf-parser = { version = "0.13", default-features = false }
